models/__init__.py
from flask_sqlalchemy import SQLAlchemy

# 创建SQLAlchemy对象

db =SQLAlchemy()

models/user.py
from sqlalchemy import Column, ForeignKey
from sqlalchemy import Integer, String
from models import db


# 模型之间的关系不需要创建第三个模型类来实现第三张关系表创建
# 创建用户和角色的关系表
user_role = db.Table('user_role',
                     Column('user_id', Integer, ForeignKey('user.id', name='user_role_fk')),
                     Column('role_id', Integer, ForeignKey('role.id', name='user_role_pk')))


# 抽象父类
class BaseModel(db.Model):
    __abstract__ = True  # 作用；不会创建模型对应的表
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(20), unique=True, nullable=True)


class Role(BaseModel):
    __tablename__ = 'role'

class QX(BaseModel):
    __tablename__ = 'qx'


class User(db.Model):
    id = Column(Integer,
                primary_key=True,
                autoincrement=True)
    phone = Column(String(20),
                   unique=True,
                   nullable=False)
    auth_key = Column(String(100),
                      nullable=False)
    nick_name = Column(String(20))
    photo = Column(String(100))

    # role_id = Column(ForeignKey('role.id'))
    # Many-to-Many 多对多关系，指定secondary设置关联的表 Table()
    roles = db.relationship(Role, secondary=user_role)

mainapp/__init__.py
from flask import Flask
import settings


app = Flask(__name__)
app.config.from_object(settings.Dev)

mainapp/views/user_v.py
import os
import uuid
from flask import Blueprint, redirect, jsonify
from flask import request, render_template
from werkzeug.datastructures import FileStorage

import settings
from models import db
from models.user import User
from utils import crypt, cache
from datetime import datetime, timedelta

blue = Blueprint('userBlue', __name__)

@blue.route('/modify', methods=['GET', 'POST'])
def modify():
    # print('request-method: ', request.method)

    token = request.cookies.get('token')
    user_id = cache.get_user_id(token)
    # 任务1；优化登录用户的相关信息存在Redis中（缓存）
    user = User.query.get(int(user_id))
    msg = ''
    if request.method == 'POST':
        # 头像上传
        # 获取上传的文件
        # user_photo必须和前端请求中文件字段名保持一致
        upload_file: FileStorage = request.files.get('user_photo')
        print('文件的名称：',upload_file.filename)
        # print('文件的长度(字节)：',upload_file.content_length)
        print('文件的类型：',upload_file.content_type)
        # 验证文件是否为图片
        if not upload_file.content_type.startswith('image/'):
            msg = '只支持图片上传'
        else:
            # 保存图片
            filename = uuid.uuid4().hex + os.path.splitext(upload_file.filename)[-1]
            filepath = os.path.join(settings.USER_DIR, filename)
            # 服务端保存上传的文件
            upload_file.save(filepath)

            # 更新用户信息
            # 保存在数据库的图片是相对于static资源访问的路径
            user.photo = 'user/'+filename
            db.session.commit()

    return render_template('user/info.html',
                           user=user,
                           msg=msg)

@blue.route('/logout',methods=['GET'])
def logout():
    # 删除redis中的token
    token = request.cookies.get('token')
    cache.clear_token(token)

    # 删除cookie
    resp = redirect('/user/login')
    resp.delete_cookie('token')

    return resp


@blue.route('/login', methods=['GET', 'POST'])
def login():
    message = ''
    if request.method == 'POST':
        phone = request.form.get('phone')
        passwd = request.form.get('passwd')

        login_user = User.query.filter(User.phone == phone,
                                       User.auth_key == crypt.pwd(passwd)).one()
        if login_user:
            # 登入成功
            # 生成token
            token = uuid.uuid4().hex
            resp = redirect('/')
            resp.set_cookie('token', token, expires=(datetime.now() + timedelta(days=3)))

            # 将token添加到redis中， token_user_id
            cache.save_token(token, login_user.id)

            return resp
        else:
            message = '查询此用户'
    return render_template('user/login.html', msg=message)

utils/__init__.py
from redis import Redis

rd = Redis(host='47.102.218.113',
           db=9,
           password='1qaz2wsx',
           decode_responses=True)

mainapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>主页</h1>
    <h3><a href="{{  url_for('userBlue.modify') }}">修改个人信息</a></h3>
</body>
</html>

mainapp/templates/user/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.nick_name }}的个人中心</title>
</head>
<body>
    <h3>修改{{ user.phone }}用户的头像</h3>

    <p>
        <img src="/static/{% if user.photo %}{{ user.photo }}{% else %}images/default_img.jpg{% endif %} "
            width="100"
            height="100">
    </p>
    <!-- 如果form表单请求的路径是当前url路径， 可以省略 action-->
    <form method="post" enctype="multipart/form-data">
        <input name="user_photo" type="file">
        <button>开始上传头像</button>
    </form>
    <P style="color: red;">
        {{ msg }}
    </P>
</body>
</html>

mainapp/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h1>用户登录页面</h1>
    <form name="login_form" action="/user/login" method="POST">
        <input name="phone" placeholder="手机号"><br>
        <input name="passwd" type="password"  placeholder="口令"><br>
        <button>登录</button>
        <a href="#">没有账号就先去注册</a>
    </form>
    <div id="val_info"  style="color: red">
        {{ msg }}
    </div>
    <script>
        function $(id){
            return document.getElementById(id)
        }
        // 设置表单提交函数
        document.forms[0].onsubmit = function (ev) {
            if(!/\d{11}/.test(this.phone.value)){
                $('val_info').innerHTML='手机号必须是为11位';
                return false;
            }
            if(!/\w{6,}/.test(this.passwd.value)){
                console.log(this.passwd.value)
                $('val_info').innerHTML='口令是包含数字和字母的至少6位的字符串';
                return false;
            }
             $('val_info').innerHTML='';
        }
    </script>
</body>
</html>